name: Test

on:
  # push:
  #   branches: [develop, main]
  workflow_dispatch:
  # pull_request:
  #   branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chronio_test

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y curl libjemalloc2 libvips42 postgresql-client

      - name: Install Google Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true
          install-dependencies: false
        id: setup-chrome

      - name: Check for Chrome and ChromeDriver
        run: |
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
          ${{ steps.setup-chrome.outputs.chromedriver-path }} --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set permissions for bin scripts
        run: chmod +x bin/*

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!";
              exit 0;
            fi;
            echo "Waiting for PostgreSQL to be ready...";
            sleep 2;
          done;
          echo "PostgreSQL failed to start.";
          exit 1;

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/chronio_test
        run: |
          bin/rails db:prepare && bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore